openapi: 3.1.0
info:
  title: Slack Knowledge Base (Local)
  version: 0.1.0
servers:
  - url: http://localhost:8000
paths:
  /search:
    get:
      operationId: searchMessages
      summary: Search Slack messages containing a keyword
      parameters:
        - in: query
          name: q
          required: true
          schema:
            type: string
        - in: query
          name: limit
          required: false
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: OK
  /channels:
    get:
      operationId: listChannels
      summary: List channels
      responses:
        '200':
          description: OK
  /channels/{channel_name}/days:
    get:
      operationId: listChannelDays
      summary: List days available for a channel
      parameters:
        - in: path
          name: channel_name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
  /channels/{channel_name}/messages:
    get:
      operationId: getChannelMessages
      summary: Get messages for a channel (optionally for a specific day)
      parameters:
        - in: path
          name: channel_name
          required: true
          schema:
            type: string
        - in: query
          name: day
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
