openapi: 3.1.0
info:
  title: Local Slack Export API
  version: 0.1.0
servers:
  - url: http://localhost:8000
paths:
  /channels:
    get:
      summary: List channels
      responses:
        '200':
          description: OK
  /users:
    get:
      summary: List users
      responses:
        '200':
          description: OK
  /channels/{channel_name}/days:
    get:
      summary: List days available for a channel
      parameters:
        - in: path
          name: channel_name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
  /channels/{channel_name}/messages:
    get:
      summary: Get messages for a channel (optionally for a specific day)
      parameters:
        - in: path
          name: channel_name
          required: true
          schema:
            type: string
        - in: query
          name: day
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
  /search:
    get:
      summary: Search messages containing text
      parameters:
        - in: query
          name: q
          required: true
          schema:
            type: string
        - in: query
          name: limit
          required: false
          schema:
            type: integer
            default: 50
      responses:
        '200':
          description: OK
